name: Build and Deploy

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 19

    - name: Build artifact and site
      run: |
        if [ -e "bee" ]; then
          source bee install doc:site
        else
          version=$(curl -SsL https://git.io/stable-bee)
          curl -SsL -o bee-${version}.jar https://jitpack.io/com/github/teletha/bee/${version}/bee-${version}.jar
          java -javaagent:bee-${version}.jar -cp bee-${version}.jar bee.Bee install doc:site
        fi

    - name: Deploy site
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: target/site

    - name: Request Releasing
      uses: GoogleCloudPlatform/release-please-action@v3
      with:
        release-type: simple
        package-name: officelove